### ISSUE TITLE
Not getting Roboto Mono in file tree :-(

### ISSUE THREAD

**Issue by octref** [teabyii/vscode-ayu#5]
![image](https://cloud.githubusercontent.com/assets/4033249/22865112/5db8e824-f12b-11e6-95fa-4fd926e87a7a.png)

Good theme though.

**Comment by eScribMac** [comment]
FWIW, I had the same problem in Sublime on Ubuntu, and it turned out that I didn't have the font installed properly. For some reason it was showing up in the editor but not the GUI, and when I correctly installed it the problem went away (I had Roboto installed instead of Roboto Mono, but the editor was correctly showing Roboto Mono). Not sure if that will be of any help to you, but worth looking in to

**Comment by pahen** [comment]
This isn't supported by VSCode yet.

**Comment by pahen** [comment]
Think this issue can be closed @teabyii
